codecov: 
 token: 25826728-480a-4de3-be4c-eee32b54e971
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
